work_logger/logger_app/urls.py
from django.conf.urls import url, include
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken.views import obtain_auth_token

from . import views


router = DefaultRouter()
router.register(r'projects', views.ProjectViewSet)
router.register(r'time_logs', views.TimeLogViewSet, 'time_logs')

app_name = 'logger_app'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]+)/$', views.DashboardView.as_view(), name='day_detail'),
    url(r'^api/', include(router.urls)),
    url(r'^api/projects/(?P<project_pk>[0-9]+)/user/(?P<user_pk>[0-9]+)$', views.assign_user),
    url(r'^register/$', views.UserCreate.as_view()),
    url(r'^rest-auth/', include('rest_auth.urls'))
]

work_logger/work_logger/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^logger/', include('logger_app.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^$', RedirectView.as_view(url='/logger/', permanent=True))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

work_logger/logger_app/models.py
from django.db import models
from django.contrib.auth.models import User
from .managers import TimeLogManager


# Create your models here.
class TimeLog(models.Model):
    """
    Models hours worked on a specific project with remarks
    """
    duration = models.FloatField()
    project = models.ForeignKey('Project', on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    remarks = models.CharField(max_length=200)
    log_date = models.DateField()
    publish_date = models.DateField(auto_now_add=True)
    objects = TimeLogManager()

    class Meta:
        ordering = ('-log_date', 'project', 'duration')

    def __str__(self):
        if self.project is not None:
            return "{} - {}: {}h".format(self.project.name, self.log_date, self.duration)
        else:
            return "{}: {}h".format(self.log_date, self.duration)

    def is_late_log(self):
        return self.publish_date > self.log_date


class Project(models.Model):
    """
    Models Projects in the system that receives work logs
    """
    name = models.CharField(max_length=200)
    assigned_users = models.ManyToManyField(User)

    class Meta:
        ordering = ('name', )

    def __str__(self):
        return self.name

    def display_total_logged_hours(self):
        total_logged_hours = 0
        for time_log in self.timelog_set.all():
            total_logged_hours += time_log.duration
        return total_logged_hours
    display_total_logged_hours.short_description = 'Total logged hours'

work_logger/logger_app/forms.py
from django import forms
from django.forms import formset_factory
from .models import Project, TimeLog


class TimeLogForm(forms.ModelForm):
    duration = forms.FloatField(
        label='Duration of Hours',
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': '(e.g. 1.5)'
        })
    )
    project = forms.ModelChoiceField(
        queryset=Project.objects.all().order_by('name'),
        required=True,
        widget=forms.Select(attrs={
            'class': 'form-control'
        })
    )
    remarks = forms.CharField(
        max_length=200,
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control'
        })
    )

    class Meta:
        model = TimeLog
        fields = ('duration', 'project', 'remarks')


TimeLogFormSet = formset_factory(TimeLogForm, extra=3)

work_logger/logger_app/views.py
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .models import TimeLog, Project
import datetime
from django.urls import reverse
from .forms import TimeLogFormSet
from django.views.generic import FormView
from django.http import HttpResponseBadRequest
from django.contrib.auth.models import User
from django.utils import timezone

# REST API Module Imports
from rest_framework import generics, viewsets, permissions
from .serializers import TimeLogSerializer, ProjectSerializer, UserSerializer
from .permissions import IsOwner, IsAssignedToProject
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response


# Create your views here.
# REST API Views
class TimeLogViewSet(viewsets.ModelViewSet):
    """
    Provides endpoints to create, read, update, and delete
    time logs.
    """
    serializer_class = TimeLogSerializer
    permission_classes = (permissions.IsAuthenticated, IsOwner, IsAssignedToProject)

    def perform_create(self, serializer):
        serializer.validated_data['user'] = self.request.user
        return super(TimeLogViewSet, self).perform_create(serializer)

    def get_queryset(self):
        queryset = TimeLog.objects.filter(user__exact=self.request.user)
        query_date = self.request.query_params.get('date', None)
        if query_date is not None:
            queryset = queryset.filter(log_date__exact=query_date)
        else:
            queryset = queryset.filter(log_date__exact=timezone.now().date())
        return queryset


class UserCreate(generics.CreateAPIView):
    """
    Endpoint that registers users into the system
    """
    queryset = User.objects.all()
    serializer_class = UserSerializer


class ProjectViewSet(viewsets.ModelViewSet):
    """
    Project view set which automatically has all CRUD operations
    as well as indexing, but only for staff members.
    """
    queryset = Project.objects.all()
    serializer_class = ProjectSerializer
    permission_classes = (permissions.IsAdminUser, permissions.DjangoModelPermissions)


@api_view(['POST', 'DELETE'])
@permission_classes((permissions.IsAdminUser, ))
def assign_user(request, project_pk, user_pk):
    """
    An admin-only endpoint that allows admin to assign users
    to a project or to remove users from a project.
    """
    project = get_object_or_404(Project, pk=project_pk)
    user = get_object_or_404(User, pk=user_pk)

    if request.method == 'POST':
        project.assigned_users.add(user)
        return Response('User {} added to project {}.'.format(user, project))

    elif request.method == 'DELETE':
        project.assigned_users.remove(user)
        return Response('User {} removed from project {}.'.format(user, project))


@method_decorator(login_required, name='dispatch')
class DashboardView(FormView):
    form_class = TimeLogFormSet
    template_name = 'index.html'
    success_url = '/'

    def dispatch(self, request, *args, **kwargs):
        """Used to validate the URL Parameters"""
        try:
            day = int(self.kwargs['day'])
            month = int(self.kwargs['month'])
            year = int(self.kwargs['year'])
        except TypeError:
            return HttpResponseBadRequest('Invalid year, month, or day in URL parameters')
        if month < 1 or month > 12:
            return HttpResponseBadRequest('Invalid month')
        if day < 1 or day > 31:
            return HttpResponseBadRequest('Invalid day')
        self.kwargs['day'] = day
        self.kwargs['month'] = month
        self.kwargs['year'] = year
        return super(DashboardView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        year = self.kwargs['year']
        month = self.kwargs['month']
        day = self.kwargs['day']
        user = self.request.user
        log_date = datetime.date(year, month, day)
        context['logs'] = TimeLog.objects.get_logs_of_day(log_date, user)
        context['projects'] = Project.objects.all()
        context['total_for_day'] = TimeLog.objects.get_total_for_day(log_date, user)
        context['total_for_month'] = TimeLog.objects.get_total_for_month(log_date, user)
        context['total_for_week'] = TimeLog.objects.get_total_for_week(log_date, user)
        return context

    def form_valid(self, formset):
        for data in formset.cleaned_data:
            if data:
                log_date = datetime.datetime(self.kwargs['year'], self.kwargs['month'], self.kwargs['day']).date()
                input_duration = data['duration']
                input_project = data['project']
                input_remarks = data['remarks']
                t = TimeLog(duration=input_duration,
                            project=input_project,
                            remarks=input_remarks,
                            log_date=log_date,
                            user=self.request.user)
                t.save()
        return redirect(reverse('logger_app:day_detail', kwargs={'year': self.kwargs['year'],
                                                                 'month': self.kwargs['month'],
                                                                 'day': self.kwargs['day']}))


@login_required
def index(request):
    today = datetime.datetime.now()
    year = today.year
    month = today.month
    day = today.day
    path = '/'.join([str(x) for x in [year, month, day]]) + '/'
    return redirect(path)

work_logger/logger_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>Work Logger - Dashboard</title>{% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block stylesheets %}{% endblock %}
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6"><h1>Work Logger App</h1></div>
            <div class="col-md-6">
            <p>
                {% if user.is_authenticated %}
                <h1><a href="{% url 'logout' %}?next={% url 'login' %}"><i class="glyphicon glyphicon-off pull-right"></i></a></h1>
                {% endif %}
            </p>
            </div>
        </div>
        <hr>
        <div class="col-sm-12">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    {% block javascripts %}{% endblock %}
</body>
</html>

work_logger/logger_app/templates/index.html
{% extends "base.html" %}
{% block stylesheets %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker.css">
{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div id="log-form" class="container-fluid">
            {% if user.first_name %}
                <h3>Hello, <span style="text-transform: capitalize">{{ user.first_name }}</span>!</h3><br>
            {% else %}
                <h3>Hello, {{ user.get_username }}!</h3><br>
            {% endif %}

            <p>Log your time below:</p><br>
            <form action="" method="post" role="form">
                {% csrf_token %}
                {{ form.management_form }}
                {% for form_instance in form %}
                    {% for error in form_instance.non_field_errors %}
                    <div class="form-group has-errors text-danger small">
                        {{ error }}
                    </div>
                    {% endfor %}
                    <div class="row">
                        <div class="col-md-2">
                            <h4>Duration</h4>
                            <div class="form-group">{{ form_instance.duration }}</div>
                            <div class="form-group has-errors text-danger small">
                                {{ form_instance.duration.errors }}
                            </div>
                        </div>
                        <div class="col-md-4">
                            <h4>Project</h4>
                            <div class="form-group">{{ form_instance.project }}</div>
                            <div class="form-group has-errors text-danger small">
                                {{ form_instance.project.errors }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <h4>Remarks</h4>
                            <div class="form-group">{{ form_instance.remarks }}</div>
                            <div class="form-group has-errors text-danger small">
                                {{ form_instance.remarks.errors }}
                            </div>
                        </div>
                    </div>
                {% endfor %}

                <button class="btn btn-default" type="Submit">Submit</button>
            </form>
            <p id="total-log">
                <strong>TOTAL LOG FOR THE DAY:
                {{ total_for_day }}
                    <span>
                        {% if total_for_day != 1 %}
                            hours
                        {% else %}
                            hour
                        {% endif %}
                    </span>
                </strong>
            </p>
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th>Duration</th>
                    <th>Project</th>
                    <th>Remarks</th>
                </tr>
            </thead>
            <tbody>
                {% for log in logs %}
                    <tr style={% if log.is_late_log %}"color: darkred;"{% else %}""{% endif %}>
                        <td>{{ log.duration }} h</td>
                        <td>
                            {% if log.project %}
                            {{ log.project }}
                            {% else %}
                            No associated project
                            {% endif %}
                        </td>
                        <td>{{ log.remarks }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="container">

            <div class="row">
                <div class="col-md-4">
                    <p>Change the date being viewed here:</p>
                    <input id='date-picker' type="text" class="form-control" placeholder="Click here">
                </div>
                <div class="col-md-4">
                    <p><strong>Total Hours Logged for Same Month:</strong></p>
                    <p><strong>{{ total_for_month }}</strong></p>
                </div>
                <div class="col-md-4">
                    <p><strong>Total Hours Logged for Same Week:</strong></p>
                    <p><strong>{{ total_for_week }}</strong></p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block javascripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            var datePicker = $('#date-picker');
            datePicker.datepicker({
                format: 'yyyy/mm/dd'
            });
            datePicker.on('changeDate', function() {
                var chosenDate = $('#date-picker').val();
                if (!(chosenDate == null || chosenDate === '')) {
                    window.location.href = "{% url 'logger_app:index' %}" + chosenDate + '/';
                }
            });
        });
    </script>
{% endblock %}